# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, main ]
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.13.1 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'cache'
        uses: actions/cache@v2
        with:
          path: |
            ~/.yarn
            ~/node_modules
            **/node_modules/**
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable

      - name: 'hardhat compile'
        env:
          DEFAULT_NETWORK: ${{ secrets.DEFAULT_NETWORK }}
        run: |
          yarn contracts build

      - name: 'build production'
        if: startsWith(${{github.ref}}, 'refs/heads/app/')
        run: |
          yarn start optimize --force 
          yarn build
    #  - run: yarn hardhat:test
    #  - name: Publish Unit Test Results
    #    uses: EnricoMi/publish-unit-test-result-action@v1
    #    if: always()
    #    with:
    #      files: testresult.xml
